# azure-pipelines.yml
trigger:
- feature-azure

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 000-S3-AD

stages:
- stage: PythonConfig
  jobs:
  - job: PythonConfigJob
    steps:
    - template: /templates/template-python.yml

- stage: runAWS
  jobs:
  - job: runAWSJob
    steps:
    - template: /templates/template-aws-cli.yml

resources:
  repositories:
    - repository: azure_devops_002
      type: git
      name: azure_devops_002/template-nodeJS
      ref:  refs/heads/main