# azure-pipelines.yml
trigger:
- feature-azure

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 000-S3-AD

resources:
  repositories:
    - repository: azure_devops_002
      type: git
      name: entorno_devco/azure_devops_002
      ref:  refs/heads/main

stages:
# - stage: PythonConfig
#   jobs:
#   - job: PythonConfigJob
#     steps:
#     - template: /templates/template-python.yml
- stage: runAWS
  jobs:
  - job: runAWSJob
    steps:
    - template: /templates/template-aws-cli.yml